[project]
authors = ["Theo van der Sluijs <theo@vandersluijs.nl>"]
channels = ["conda-forge"]
description = "A simple python mailer for Umami reports"
name = "umami_mailer"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
report = "python umami_report.py"

[dependencies]
requests = "*"
jinja2 = ">=3.1.5,<4"
weasyprint = ">=62.3,<63"
